### ISSUE TITLE
Function specs 

### ISSUE THREAD

**Issue by huan-ds** [UBC-MDS/pytweet#4]
@#Hi, 

I did some research today. For the functions that we are planning to develop, `get_tweets`, `hashtag_viz`, and `sentiment` seem safe to go with. 

I found the emoji extraction is not that easy because of the encoding issues. I tried on a toy dataset. The encoding and decoding are annoying. I didn't find a good resource to refer to. This function is a potential risk. So I suggest we can replace this function with timeline analysis or retweet analysis. 

We can discuss this at tomorrow's group meeting.

**Comment by mmyz88** [comment]
Per discussion, will do timeline analysis and hashtag analysis instead.
