### ISSUE TITLE
Function 3: Tweets Sentiment analysis

### ISSUE THREAD

**Issue by yuanxiongbear** [UBC-MDS/pytweet#7]
Hello Team, 

I have found a couple of guides about how to do sentiment analysis using python. Basically there are a couple of steps of data wrangling, and then train a model based on the sample data. This is interesting and also doable but difficult to fit everything into just one function. Am I allowed to do this with multiple functions? 

For your reference here are the links for how to do sentiment analysis with python (they are more or less the same): 
https://towardsdatascience.com/step-by-step-twitter-sentiment-analysis-in-python-d6f650ade58d
https://www.pluralsight.com/guides/building-a-twitter-sentiment-analysis-in-python
https://www.digitalocean.com/community/tutorials/how-to-perform-sentiment-analysis-in-python-3-using-the-natural-language-toolkit-nltk

**Comment by huan-ds** [comment]
Yes, I think it is completely okay to have more functions. 
Also, I found 2 resources yesterday for your reference.
https://towardsdatascience.com/a-guide-to-mining-and-analysing-tweets-with-r-2f56818fdd16
https://monkeylearn.com/blog/sentiment-analysis-of-twitter/

**Comment by yuanxiongbear** [comment]
Thank you @huan-ds
